version: "2"

services:
  stats:
    image: matthewbaggett/netmon-stats
    build: .
    volumes:
      - ./:/app
    environment:
      - TESTED_SERVICE_LABEL=Example
      - MYSQL_HOST=mysql
      - MYSQL_USER=netmon
      - MYSQL_PASSWORD=8j2o5N8Ctb5v2kQ
      - MYSQL_DATABASE=netmon
    ports:
      - '10000:80'
